### ISSUE TITLE
No provider found for DateAdapter. 

### ISSUE THREAD

**Issue by mahpour** [SaturnTeam/saturn-datepicker#1]
Hi 

I followed the instructions you provided but I get the following error upon rendering the component:

```ERROR Error: MatDatepicker: No provider found for DateAdapter. You must import one of the following modules at your application root: MatNativeDateModule, MatMomentDateModule, or provide a custom implementation.
    at createMissingDateImplError (saturn-datepicker.js:39)
    at new MatDatepickerInput (saturn-datepicker.js:2214)
    at createClass (core.js:12480)
    at createDirectiveInstance (core.js:12315)
    at createViewNodes (core.js:13776)
    at createEmbeddedView (core.js:13653)
    at callWithDebugContext (core.js:15090)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (core.js:14402)
    at TemplateRef_.createEmbeddedView (core.js:11718)
    at ViewContainerRef_.createEmbeddedView (core.js:11430)
```
I have the following modules imported in my sub module:

```
import {MatNativeDateModule, MatSliderModule, DateAdapter} from '@angular/material';
import { MatDatepickerModule } from 'saturn-datepicker';
...
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatToolbarModule,
    MatSelectModule,
    MatTabsModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatCardModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatListModule,
    MatMenuModule,
    MatIconModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSliderModule
  ],

```

Any suggestions?

**Comment by SaturnTeam** [comment]
You need to import `MatNativeDateModule` or `MatMomentDateModule` from `@angular/material`

**Comment by mahpour** [comment]
But as I mentioned I have already imported it.

**Comment by SaturnTeam** [comment]
try import MatNativeDateModule from 'saturn-datepicker'

**Comment by SaturnTeam** [comment]
It's strange. I use MatNativeDateModule from '@angular/material'. I remember I had the same problem, but I fixed it before publish (I use the version from npm).

**Comment by SaturnTeam** [comment]
Try version 0.0.2

**Comment by Krishna-Agrawal** [comment]
Hi @SaturnTeam 
I am still getting that issue in 0.0.2

**Comment by SaturnTeam** [comment]
@Krishna-Agrawal And have you imported MatNativeDateModule too? I have no idea what is the difference. I have the same importing module order. Could you try to import MatNativeDateModule in AppModule?

**Comment by Krishna-Agrawal** [comment]
Yeah, imported MatNativeDateModule even tried MatMomentDateModule too.

**Comment by SaturnTeam** [comment]
Could you try in app module?

   ```
 providers: [
        MatNativeDateModule,
    ],
```

**Comment by Krishna-Agrawal** [comment]
I tried in app module only,
Btw why in providers, it's a module which needs to be imported like 
```
imports: [
     MatNativeDateModule
 ]
```

**Comment by SaturnTeam** [comment]
yes, but in providers it can be imported too, no any errors:)

**Comment by SaturnTeam** [comment]
Try in new version 1.0.1

**Comment by kamleshwebtech** [comment]
Import 'MatNativeDateModule' is the only solution, i found yet. It works.

**Comment by anbiniyar** [comment]
I narrowed down the issue. The reason it's not working is the DateAdapter,MAT_DATE_FORMATS and MAT_DATE_LOCALE are being redefined in the library which is why it doesn't work out of the box. We are essentially dealing with two classes with same name situation. You may use the following workaround.

```typescript
import {
  DateAdapter as SatDateAdapter,
  MAT_DATE_FORMATS as SAT_DATE_FORMATS,
  MAT_DATE_LOCALE as SAT_DATE_LOCALE,
  SatDatepickerModule,
} from 'saturn-datepicker';

@NgModule({
  providers: [
    {
      provide: SatDateAdapter,
      useExisting: DateAdapter,
    },
    { provide: SAT_DATE_FORMATS, useExisting: MAT_DATE_FORMATS },
    { provide: SAT_DATE_LOCALE, useExisting: MAT_DATE_LOCALE },
  ],
})
export class SatDatAdapterModule { }
```
I have also opened the following issue to figure out what might be the best way forward. https://github.com/SaturnTeam/saturn-datepicker/issues/69

**Comment by leckey-smart-walker** [comment]
When using Saturn Datepicker you must import `DateAdapter` from `saturn-datepicker`, not `@angular/material`

**Comment by eoinmullan** [comment]
When using Saturn Datepicker you must import `MAT_DATE_FORMATS` and `MAT_DATE_LOCALE` from `saturn-datepicker`, not `@angular/material`

**Comment by manojind** [comment]
I got, Here working fine 
Just import the modules in APP.MODULE.TS file 

import {MatDatepickerModule} from '@angular/material/datepicker';
import {MatNativeDateModule} from '@angular/material/core';
import {MatInputModule} from '@angular/material/input';

 imports: [
    MatDatepickerModule
,MatNativeDateModule,MatInputModule 
 ]

HTML : 
You need to wrap element with <FORM > Tag
