### ISSUE TITLE
Error with `ng build --prod`

### ISSUE THREAD

**Issue by daveo1001** [SaturnTeam/saturn-datepicker#10]
There's a small chance I just don't know what I'm doing but when I run `ng build --prod` I get the following error:
```ERROR in : Unexpected value 'SatNativeDateModule in C:/route/to/application/node_modules/saturn-datepicker/datetime/index.d.ts' imported by the module 'AppMaterialModule in  C:/route/to/application/src/app/app-material.module.ts'. Please add a @NgModule annotation.```

Any tips or ideas?

**Comment by SaturnTeam** [comment]
yep. it's an awful package made by ng-packagr. I'll try a new version in a few days

**Comment by daveo1001** [comment]
Ha! thanks! I'll patiently await the change :D

**Comment by SaturnTeam** [comment]
solved in 1.1.8
