### ISSUE TITLE
calendarFooterComponent overflows the satCalender container

### ISSUE THREAD

**Issue by SteffenSchwaiger** [SaturnTeam/saturn-datepicker#100]
It seems like that if the number of calendar rows is 6, the footer gets pushed out the satCalendar container.

Tested on:
Chrome Version 76.0.3809.132 (64-Bit)
Firefox 68.0.2 (64-Bit)

The bug is also present in the official example: [https://stackblitz.com/edit/angular-4cfnyl?file=src%2Fapp%2Fapp.component.scss](https://stackblitz.com/edit/angular-4cfnyl?file=src%2Fapp%2Fapp.component.scss)

![image](https://user-images.githubusercontent.com/5320760/64100004-f27cbf80-cd6a-11e9-9625-d4562e8a9eca.png)

**Edit:**
Fixed the problem by adding the following styles:

> .mat-datepicker-content .mat-calendar {
>   height: auto;
> 
>   .mat-calendar-footer {
>     padding: 0 1rem 1rem;
>   }
> }

Especially the first one is crucial to fix the overflow of the footer component. Maybe you should add the _height: auto_ property to the package by default. Also the official example on Stackblitz needs to be fixed. Maybe I find the time in the next few days to make a pull request.

**Comment by olliechick** [comment]
Has this been fixed?
