### ISSUE TITLE
Build failing with 1.1.8 (5.2.10)

### ISSUE THREAD

**Issue by daveo1001** [SaturnTeam/saturn-datepicker#11]
Uncaught TypeError: Object(...) is not a function
    at eval (saturn-datepicker.js:679)
    at Object../node_modules/saturn-datepicker/fesm5/saturn-datepicker.js (vendor.bundle.js:7480)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (app-material.module.ts:39)
    at Object../src/app/app-material.module.ts (main.bundle.js:28)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (app.module.ts:11)
    at Object../src/app/app.module.ts (main.bundle.js:66)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (main.ts:4)

client:147 [WDS] Warnings while compiling.
warnings @ client:147
client:153 ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
2374:35-41 "export 'inject' was not found in '@angular/core'
 @ ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
 @ ./src/app/app-material.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts

warnings @ client:153
client:153 ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
37:11-17 "export 'inject' was not found in '@angular/core'
 @ ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
 @ ./src/app/app-material.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts

warnings @ client:153
client:153 ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
679:55-71 "export 'defineInjectable' was not found in '@angular/core'
 @ ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
 @ ./src/app/app-material.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by SaturnTeam** [comment]
@angular/material 6.0 is required

**Comment by daveo1001** [comment]
yup, had to get everything to 6.
Works like a charm now though.
Thank you!
