### ISSUE TITLE
Drag for Selection and disable text selection

### ISSUE THREAD

**Issue by MunkiWinchester** [SaturnTeam/saturn-datepicker#111]
Hi!

I would like to request/suggest that you can select a range by dragging over the dates instead or also by clicking on one date and then the other.

Also I would like to have an option (or per default) to disable the selection of text (eg. the date numbers in the calendar.

Best regards
Munki

**Comment by SaturnTeam** [comment]
> by dragging over the dates 
Very rare case to implement

>Also I would like to have an option (or per default) to disable the selection of text (eg. the date numbers in the calendar.

You can do it by adding css rules
