### ISSUE TITLE
How limit max range could user select?

### ISSUE THREAD

**Issue by lubo08** [SaturnTeam/saturn-datepicker#114]
Please help is there way how limit maximum range user can select? For example, do not allow users to choose bigger range than 30 days? Just to because not alow user pickup to big data transfer?

**Comment by SaturnTeam** [comment]
use custom validation rules. Similar to https://material.angular.io/components/datepicker/overview#date-validation

**Comment by lubo08** [comment]
Thank you for help. I will try it.

**Comment by varun1233** [comment]
Did you find a solution for it? If yes can you please share?
