### ISSUE TITLE
<mat-calendar [selected]="selectedDate" [rangeMode]="true"></mat-calendar>

### ISSUE THREAD

**Issue by DennyReM** [SaturnTeam/saturn-datepicker#115]
Hi! it looks like selected doesn`t work for inline view ranged mode trying to put as "selectedDate"
 this.selectedDate = {begin: new Date(2019, 11, 4), end: new Date(2019, 11, 30)};
You can try to do the same in DEMO, its not patching range into calendar

**Comment by olehleskiv** [comment]
Any updates? Have the same issue

**Comment by SaturnTeam** [comment]
I've not investigated this issue. But you can:)

**Comment by edmilsonlani** [comment]
Use beginDate and endDate.

`<sat-calendar [rangeMode]="true"
                      [beginDate]="inlineRange.begin"
                      [endDate]="inlineRange.end"
                      (dateRangesChange)="inlineRangeChange($event)"
                      (beginDateSelectedChange)="inlineBeginChange($event)">
        </sat-calendar>`
