### ISSUE TITLE
Can't use [value] to set calendar dates. 

### ISSUE THREAD

**Issue by Defmetalhead** [SaturnTeam/saturn-datepicker#124]
public calendarDate = { begin: new Date(2020, 1, 1), end: new Date(2020, 1, 5) };

<input matInput (dateChange)="handleDateChange($event.value)"
               [min]="minDate" placeholder="Choose a date" [value]="calendarDate"
               [disabled]="activityEngineService.isLoadingStream.value" [satDatepicker]="datePicker" class="calendar-input">

I just want dates to be pre-selected when opening the calendar.

**Comment by SaturnTeam** [comment]
please double-check your code. Initial value seems correct
