### ISSUE TITLE
Compatibility with Angular 9

### ISSUE THREAD

**Issue by cmdaniel** [SaturnTeam/saturn-datepicker#126]
Hi,
I'm trying to update my apps to Angular 9. When I tried to execute the ng update, these messages appear:
   Package "saturn-datepicker" has an incompatible peer dependency to "@angular/cdk" (requires "^8.2.0", would install "9.0.0").
                  Package "saturn-datepicker" has an incompatible peer dependency to "@angular/material" (requires "^8.2.0", would install "9.0.0

**Comment by SaturnTeam** [comment]
I think my datepicker would work. But not sure. It's time to update, but I quite busy in this week. Please remind me later, if I forget

**Comment by Carniatto** [comment]
@SaturnTeam remembering you now!

**Comment by SaturnTeam** [comment]
Sorry, I forgot. I hope during this week I'll update finally. Publishing package is the most hardest thing

**Comment by cmdaniel** [comment]
That is a great news! Thank you for your attention and glad to test new version when it was available.

**Comment by WojciechSlyp** [comment]
I'm getting this when installed alongside Angular 9 despite the warnings:
![image](https://user-images.githubusercontent.com/49943725/74748867-8256ed00-5269-11ea-831e-308596c4928a.png)

**Comment by cmdaniel** [comment]
Hi, while the official solution is not available, we did a small change into the js just to be possible to compile, run and debug the whole project.

At **node_modules** directory, look for:
 **saturn-datepicker > fesm2015 > saturn-datepicker.js**

Then, just change the SatCalendar scope, from:

**let** SatCalendar = class ....

to

**var** SatCalendar = class ....


<img width="1305" alt="sat-calendar-ng9" src="https://user-images.githubusercontent.com/5529188/74831828-c6db9a80-52f4-11ea-8cb2-ff46aa48a76f.png">

**Comment by aliektlee** [comment]
Ride on @cmdaniel solution, it works.
However in my case is that since the ng will compile all packages in node_modules folder and it a folder likes this
![image](https://user-images.githubusercontent.com/17852564/75059259-8dcf4000-5517-11ea-8939-95edf4eafbe1.png)
I have to update the file(saturn-datepicker.js) within this folder directly and it works the same.
If you haven't that folder that means the ng not yet compile the saturn-datepicker, just follow @cmdaniel solution to update the file.
Thanks @cmdaniel a lot.

**Comment by NRaf** [comment]
Hey @SaturnTeam, any progress on the upgrade?

**Comment by SaturnTeam** [comment]
@NRaf 8.0.5

**Comment by MikeProcudin** [comment]
This likely means that the library which declares SatDatepickerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking 
with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by MikeProcudin** [comment]
Non of the above helped either ...
![Untitled](https://user-images.githubusercontent.com/19872423/77125287-4320e500-6a3d-11ea-9f98-f62b9652bad5.png)
![Untitled1](https://user-images.githubusercontent.com/19872423/77125289-43b97b80-6a3d-11ea-97ef-444bae861374.png)
