### ISSUE TITLE
local month names?

### ISSUE THREAD

**Issue by pawmel** [SaturnTeam/saturn-datepicker#13]
Hey guys, 
thank you for this plugin, it is very very useful feature. I have a quesion:
is it possible to use local month/day/year/week names?

with normal datepicker I used something like this:
`providers: [
    InvoiceService, {provide: MAT_DATE_LOCALE, useValue: 'pl'},
    {provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]},
    {provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS}
  ]`

also, will saturn datepicker will be included in future material releases?

**Comment by SaturnTeam** [comment]
#12

**Comment by SaturnTeam** [comment]
> will saturn datepicker will be included in future material releases?
I tried, but it's required a lot of changes before merging

**Comment by pawmel** [comment]
ng serve|build --locale=fr
//bash: build: command not found//

seems not working for me after reloading :(

**Comment by pawmel** [comment]
is it possible to set the locale in code?

**Comment by SaturnTeam** [comment]
see #12 and #8 
`serve|build` means  `ng serve --locale=ru` and `ng build --locale=ru` It's better to set locale via command line, because in that case, all components, pipes and service will get the same locale, and also html tag will have properly lang tag `<html lang="ru">`. But it may be not working in serve mode.

**Comment by pawmel** [comment]
1. Is it possible to hardcode the language?
2. Unknown option: '--locale' -> im getting after: ng build --configuration=prod  --output-hashing none --base-href /portal/ --locale=ru

**Comment by SaturnTeam** [comment]
see #8 , and try `--locale ru`

**Comment by pawmel** [comment]
thank you, it is working now.
this was also helpful  - https://github.com/angular/material2/blob/master/src/material-examples/datepicker-locale/datepicker-locale-example.ts
