### ISSUE TITLE
It's not possible to tracking second date by mouse over

### ISSUE THREAD

**Issue by m-farahmand** [SaturnTeam/saturn-datepicker#14]
In other date-range components after selecting first date by moving mouse over calendar space between first date til current date which is under mouse pointer has been colorize like [this](https://stackblitz.com/angular/aknkygyymgy) sample of ng-bootstrap.
Any way, Is there any option to do something like that?

**Comment by SaturnTeam** [comment]
Temporary no. May be I'll do it

**Comment by sp33dlink** [comment]
The Dart-Material-Components do this as well: https://dart-lang.github.io/angular_components_example/#material_datepicker

**Comment by sancaruso** [comment]
I propose a pull request that would close this issue: https://github.com/SaturnTeam/saturn-datepicker/pull/56

**Comment by SaturnTeam** [comment]
Resolved in 7.1.0
