### ISSUE TITLE
How to change date format?

### ISSUE THREAD

**Issue by ATKeit** [SaturnTeam/saturn-datepicker#15]
Current default date format is 'mm/dd/yyyy'.
I want to change like 'yyyy-mm-dd'.
How I can change this?

**Comment by SaturnTeam** [comment]
Accroding material datepicker documentation, but import constants from `saturn-datepicker`. Also see #13

**Comment by jesnasali** [comment]
@SaturnTeam Can you explain more details? tried to import constants from saturn-datepicker but it didn't work.

**Comment by SaturnTeam** [comment]
See related issues

**Comment by SaturnTeam** [comment]
`
        {provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]},
        {provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS},
`
