### ISSUE TITLE
Compatibility with Angular Material 5

### ISSUE THREAD

**Issue by irinelpascu** [SaturnTeam/saturn-datepicker#17]
In my current application I am using Angular 5 and Material 5. I tried to install saturn-datepicker and I get errors. Does it have a version that is compatible with v5? 

WARNING in ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
679:55-71 "export 'defineInjectable' was not found in 'angular/core'

**Comment by SaturnTeam** [comment]
Sorry, but it's not possible to run it with angular 5 any more. If you really need, try to use old *source* code.06.06.2018, 14:35, "Irinel Pascu" <notifications@github.com>:In my current application I am using Angular 5 and Material 5. I tried to install saturn-datepicker and I get errors. Does it have a version that is compatible with v5?
WARNING in ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
679:55-71 "export 'defineInjectable' was not found in '<gh:team-mention org="angular" team="core">'

**Comment by SaturnTeam** [comment]
https://github.com/SaturnTeam/saturn-datepicker/tree/d820f92f0cf037b673699d90fc470e6c7bfc0095
Use this code

**Comment by rssravya57** [comment]
The link points to the latest code base , Is it compatible with angular 5 and material 5 ?

**Comment by SaturnTeam** [comment]
yes

**Comment by rssravya57** [comment]
@SaturnTeam : I tried to use the latest version of saturn-datepicker for my project (angular 5 and material 5 ) but got below error :
 WARNING in ./node_modules/saturn-datepicker/fesm5/saturn-datepicker.js
2374:35-41 "export 'inject' was not found in '@angular/core

So i used saturn-datepicker-1.0.7 which supported angular 5 , It worked great with my project but when i do  build --prod , It throws error : 
ERROR in : Unexpected value 'SatDatepickerModule in C:/Users/srachakonda/git/rcm-client-repo3/rcm-client/node_modules/saturn-datepicker/datepicker/datepicker-module.d.ts' imported
by the module 'SharedModule in C:/Users/srachakonda/git/rcm-client-repo3/rcm-client/src/app/core/shared/shared.module.ts'. Please add a @NgModule annotation.

Please suggest me how can i use this component for Angular 5 and also be able to build prod

**Comment by SaturnTeam** [comment]
source code is working. not package

**Comment by rssravya57** [comment]
So the only way to get saturn-datepicker working and build to prod is after upgrading to angular 6 . Right ?

**Comment by SaturnTeam** [comment]
right
