### ISSUE TITLE
404 not found: saturn-picker@latest

### ISSUE THREAD

**Issue by rhanb** [SaturnTeam/saturn-datepicker#18]
Hi,

When I try to install the package, an error occurs:

```
npm i saturn-picker --save
npm ERR! code E404
npm ERR! 404 Not Found: saturn-picker@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rhanb/.npm/_logs/2018-06-07T09_27_49_019Z-debug.log
```

When I go to the [npm package page](https://www.npmjs.com/package/saturn-datepicker) and I click the [github link](https://github.com/TheSaturn/saturn-datepicker) I get a 404 too. The username in the url is wrong, it's `Saturn` while it should be `Team`.

#### Installation: 

` npm i https://github.com/SaturnTeam/saturn-datepicker --save`

#### Import:

`import {SatDatepickerModule} from 'saturn-datepicker/saturn-datepicker/src/datepicker';`

**Comment by rhanb** [comment]
The issue comes from the latest version: `6.0.1`, installing `6.0.0` works fine.

`npm i saturn-datepicker@6.0.0 --save`

**Comment by SaturnTeam** [comment]
you tried to install package with wrong name

**Comment by rhanb** [comment]
@SaturnTeam  ok I see, I guess it is `sat-datepicker`? it's not in the README

**Comment by SaturnTeam** [comment]
it is saturn-datepicker
