### ISSUE TITLE
Date range not highlighted on the picker on value init

### ISSUE THREAD

**Issue by etiennecrb** [SaturnTeam/saturn-datepicker#21]
Hello,

Thanks a lot for this great component that I use in several apps. When I use the `[value]` attribute to initialize input value, the date range is not highlighted when the picker is opened.

```html
<input
  matInput
  placeholder="Choose a date"
  [satDatepicker]="picker"
  [value]="date"
>
<sat-datepicker #picker [rangeMode]="true"></sat-datepicker>
<sat-datepicker-toggle matSuffix [for]="picker"></sat-datepicker-toggle>
```

![capture du 2018-07-03 17-55-30](https://user-images.githubusercontent.com/12871063/42230966-8bcad03a-7eea-11e8-8574-296710a6c544.png)

[DEMO](https://stackblitz.com/edit/angular-qwm5ke)

Thanks

**Comment by SaturnTeam** [comment]
the demo is not updated. do you have the same behavior on the latest version?

**Comment by etiennecrb** [comment]
I have updated the stackblitz to use the latest version, it presents the same behaviour. Check it here: https://stackblitz.com/edit/angular-qwm5ke

**Comment by SaturnTeam** [comment]
Thank you for example. I'll check what is wrong later.
Temporary you can use ngModel or formControl binding. WIth ngModel colors is ok https://stackblitz.com/edit/angular-qfyjar?file=src/app/hello.component.ts

**Comment by SaturnTeam** [comment]
I've found what is wrong. Update soon
