### ISSUE TITLE
Default format

### ISSUE THREAD

**Issue by sebastianmusial** [SaturnTeam/saturn-datepicker#23]
Hello,
I can't change date format in the input. 
I changed global date format like in example: https://material.angular.io/components/datepicker/overview#customizing-the-parse-and-display-formats. It's works only for the standard datepickers from Material UI.

Is it possible in this library?

**Comment by SaturnTeam** [comment]
See closed issues12.07.2018, 17:03, "Sebastian Musiał" <notifications@github.com>:Hello,
I can't change date format in the input.
I changed global date format like in example: https://material.angular.io/components/datepicker/overview#c…. It's works only for the standard datepickers from Material UI.
Is it possible in this library?

**Comment by sebastianmusial** [comment]
Thanks, for the quick reply! Its works! ✌️
