### ISSUE TITLE
Apply Date Format

### ISSUE THREAD

**Issue by pororo12990** [SaturnTeam/saturn-datepicker#24]
How Can I apply my date format to saturn datepicker?

example that I apply to mat-datepicker: 
providers: [
    {provide: DatetimeAdapter, useClass: MomentDatetimeAdapter},
    {provide: MAT_DATETIME_FORMATS, useValue: DateFormat},
],

**Comment by SaturnTeam** [comment]
as same as for material, just import constants from 'saturn-datepicker'

 `import { DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE, SatDatepickerModule } from 'saturn-datepicker'`

**Comment by pororo12990** [comment]
Got it! :)
