### ISSUE TITLE
Saturn datepicker v.1.1.0 fails building in aot - Can;t resolve all parameters for SatCalendar

### ISSUE THREAD

**Issue by petr-konopelko** [SaturnTeam/saturn-datepicker#25]
Hello guys, thank a lot for the module. 
I faced the situation when saturn-datepicker fails building in aot.
Here is the image of error
![image](https://user-images.githubusercontent.com/24682370/43636279-4c8207de-971a-11e8-8427-c7f5dfc19b04.png).
Can you help? If it is needed I'll provide more information

**Comment by SaturnTeam** [comment]
Known issue. Sorry, but there is no way to make it workable until 6.0.2

**Comment by SaturnTeam** [comment]
but you can try 1.1.7
