### ISSUE TITLE
Sunday as first day of week

### ISSUE THREAD

**Issue by duard** [SaturnTeam/saturn-datepicker#26]
I set my angular app to pt-BR (Brasilian Portuguese) and everything works with Material Design, this is my MatDatePicker using MD2, Sunday (Domingo in portuguese is the first day)

![screenshot from 2018-08-05 09-54-06](https://user-images.githubusercontent.com/36894/43686050-9f55893c-9895-11e8-946a-504bbb0af310.png)

But when I use saturn-datepicker the Monday (Segunda) is the first day 

![screenshot from 2018-08-05 09-53-49](https://user-images.githubusercontent.com/36894/43686059-bcf9f04a-9895-11e8-9261-6a1a1def7a43.png)

How can I set the saturn to work like material ?

**Comment by SaturnTeam** [comment]
So, Brasilian Portuguese's week starts from Sunday?

**Comment by duard** [comment]
Yes man, just like in that screenshot of mat-datepicker ... the D is DOMINGO, and it is the first day on week.

**Comment by SaturnTeam** [comment]
all pt ( Portuguese) starts from Sunday or pt-BR (Brasilian Portuguese) only?

**Comment by duard** [comment]
I dont know in pt-PT, but in pt-Br D (Domingo) need to be the first day, or, this can be a configurable feature.

**Comment by SaturnTeam** [comment]
6.0.4

**Comment by pschoro** [comment]
So how do you config to start on Monday... I did not get the solutuion if I want to start on Monday ?
