### ISSUE TITLE
Use ngx-mask 

### ISSUE THREAD

**Issue by duard** [SaturnTeam/saturn-datepicker#27]
I would like to use 
https://github.com/JsDaddy/ngx-mask  

`import { NgxMaskModule } from 'ngx-mask';
`
to mask my input field. Is there another way to mask the input ?

**Comment by SaturnTeam** [comment]
I have no idea

**Comment by duard** [comment]
Is there a way to mask the input ?

**Comment by SaturnTeam** [comment]
Never tried. But I recommend to use moment js adapter (see readme)

**Comment by duard** [comment]
How can I use moment to mask the input fields ? Can you show me ?

**Comment by SaturnTeam** [comment]
No. Try it on youself
