### ISSUE TITLE
How to capture on Changed event?

### ISSUE THREAD

**Issue by robherman** [SaturnTeam/saturn-datepicker#29]
Hi, I can't find a way to capture the range when it is selected. I tried using (change) on the input, selectedChanged on the datepicker, but nothing. Is there any event to do so?

Example:
`<mat-form-field>
    <input (click)="picker.open()" matInput [placeholder]="labelText" [satDatepicker]="picker" [ngModel]="date">
    <sat-datepicker (selectedChanged)="dateChanged($event)" #picker [rangeMode]="true">
    </sat-datepicker>
    <sat-datepicker-toggle matSuffix [for]="picker"></sat-datepicker-toggle>
</mat-form-field>`

**Comment by robherman** [comment]
Nevermind. Found it here: https://stackblitz.com/edit/angular-b23dak?file=app%2Fdatepicker-value-example.html

**Comment by JayashreeKrishanveni** [comment]
How to return only the date value ? The time also gets printed.

**Comment by SaturnTeam** [comment]
> How to return only the date value ? The time also gets printed.
> And is there any event to print all the values in the selected range of date ?

Datepicker returns a structure with two dates. In the same way as material datepicker
