### ISSUE TITLE
Do not close the date selector after selection  

### ISSUE THREAD

**Issue by ThibaudAV** [SaturnTeam/saturn-datepicker#30]
Do you think it would be useful to add an option allowing not to close the selector after the selection of the 2nd date? 
To make it easier to correct and check the range
We leave the selection when we click outside the datepicker

Do you have any ideas to achieve this behavior without changing the lib?

**Comment by SaturnTeam** [comment]
the range can be seen in date input

**Comment by ThibaudAV** [comment]
Yeah, but not in a colorful way. 
We had several people tested and it's often an element that came back

**Comment by ThibaudAV** [comment]
Thank you
