### ISSUE TITLE
is it possible to set and don`t let user change begin value?

### ISSUE THREAD

**Issue by DennyReM** [SaturnTeam/saturn-datepicker#32]
I need to make user able to choose range of date only from a specific date is it possible ? :)

**Comment by SaturnTeam** [comment]
yes. My datepicker is based on Material datepicker, and have 100% support of min/max and other parameters. See official documentation about that.

**Comment by DennyReM** [comment]
yes, but i need to make, for example, from server i got date 20th of june and i need to made user to choose date 20th of june - ...

**Comment by SaturnTeam** [comment]
I don't see a problem

**Comment by ThibaudAV** [comment]
🤔 no I don't think it's possible to lock the 1st selected date without changing the lib

**Comment by SaturnTeam** [comment]
example: https://stackblitz.com/edit/angular-3lkegw?file=src/app/hello.component.ts 
API: https://material.angular.io/components/datepicker/api

**Comment by deepakkj6** [comment]
> yes, but, for example, from server i got date 20th of june and i need to made user to choose date 20th of june - ... and user shouldnt be able to change start date

@DennyReM Did you found any solution for this?
