### ISSUE TITLE
Limit selectable range with [max] and [min] 

### ISSUE THREAD

**Issue by aberbenni** [SaturnTeam/saturn-datepicker#33]
Is there any way to use [max] and [min] like in mat-datepicker? https://github.com/angular/material2/blob/master/src/material-examples/datepicker-min-max/datepicker-min-max-example.html

**Comment by SaturnTeam** [comment]
Yes, it's fully support original angular material datepicker API https://material.angular.io/components/datepicker/api

**Comment by aberbenni** [comment]
Thanks

**Comment by AlonsoK28** [comment]
> Yes, it's fully support original angular material datepicker API https://material.angular.io/components/datepicker/api

This can be used with **Range date inline**?
