### ISSUE TITLE
Customize calendar header using [calendarHeaderComponent]

### ISSUE THREAD

**Issue by arihs** [SaturnTeam/saturn-datepicker#35]
I am trying to customize the Sat Datepicker calendar header using my own component, but it is ignoring the Input.

This does not work:
`<sat-datepicker #picker [calendarHeaderComponent]="exampleHeaderComponent" [rangeMode]="true"></sat-datepicker>`

But it does work with Mat Datepicker: 
`<mat-datepicker #picker [calendarHeaderComponent]="exampleHeaderComponent"></mat-datepicker>`

What am I doing wrong?

**Comment by SaturnTeam** [comment]
My bad. I'll try to fix now or tommorow

**Comment by SaturnTeam** [comment]
try 6.1.1. if it's not working, please create a demo https://stackblitz.com/edit/angular-4cfnyl

**Comment by arihs** [comment]
Sorry, but it's still not working. Now, the entire datepicker box that opens is empty.

I created a demo - basically an exact copy of material design's customized header. 
(https://material.angular.io/components/datepicker/overview#customizing-the-calendar-header): See 
 https://stackblitz.com/edit/angular-zxjajr

Thanks for you help! It's much appreciated.

**Comment by SaturnTeam** [comment]
example from angular material not working too :)
You forgot to configure NgModule and import class from `saturn-datepicker` 

here is working example: 
https://stackblitz.com/edit/angular-ecwjqo?file=src/app/app.module.ts

**Comment by arihs** [comment]
Thanks you!

**Comment by arihs** [comment]
Is there a way to EDIT the calendarHeader component, rather than REPLACE it entirely? [Or, alternatively, is it possible to reuse the date selection (dropdown  and fwd/bck navigation for months) in my replacement header component? (I don't want to have to rewrite that)] 
I am trying to add a simple toggle switch to the calendar header (yes, it has to be in the calendar component).

**Comment by SaturnTeam** [comment]
No, but you can copy-paste source code of original header

**Comment by arihs** [comment]
There's no way of extending SatCalendarHeader or MatCalendarHeader?

**Comment by SaturnTeam** [comment]
Extending components is not thing that angular can do now (if I remember correctly).

**Comment by arihs** [comment]
Update: I did extend SatCalendarHeader on my customHeaderComponent and it works like a charm. 
Thanks!

**Comment by Imansh338** [comment]
I have a similar Problem, I am trying to implement the calenderHeaderComponent from an existing mat datepicker into a sat datepicker. but the pop-up showing up blank white. the error on console is :

ERROR Error: StaticInjectorError(AppModule)[ExampleHeader -> MatCalendar]: 
  StaticInjectorError(Platform: core)[ExampleHeader -> MatCalendar]: 
    NullInjectorError: No provider for MatCalendar!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get

any Advice! Thanx 👍
