### ISSUE TITLE
Separate sat-calendar

### ISSUE THREAD

**Issue by tompetko** [SaturnTeam/saturn-datepicker#40]
Hey,

I'd love to use `sat-calendar` without input like material `mat-calendar`. Something like this:
`<sat-calendar [rangeMode]="true" [selected]="range"></sat-calendar>` but styles are not being applied to selected range. I know, this is probably not the way, how it should be used, but it wold be nice to have this ability like `mat-calendar` has.

**Comment by SaturnTeam** [comment]
It's strange. Have you tried import styles in your component or global stylesheet?
```
@import '~saturn-datepicker/theming';
@include sat-datepicker-theme($theme);
```

**Comment by tompetko** [comment]
I did it. I gave a quick view on source code and it seems, `sat-calendar` could not be used independently. The problem, why range was not correctly displayed was due to invalid calendar state. When I was trying to select range, I noticed `begin` and `end` dates were equal every time.

In method `_dateSelected` (https://github.com/SaturnTeam/saturn-datepicker/blob/d64c8de0b614e1cb5673b2376f33ca2d302d0310/saturn-datepicker/src/datepicker/calendar.ts#L388-L405) are `begin` and `end` dates set in first step of range selection. On second click, `end` date is not set and `dateRangesChange` event is fired.

I've managed to make it work: https://angular-2w1hhl.stackblitz.io. It would be nice to have all helpful methods already in `sat-calendar` like `setRange` method present in my example, that can set range programatically.

**Comment by beyondsanity** [comment]
Hello,

Thanks for the fine library!

I'm facing similar issues trying to use sat-calendar inline.
When Using the "rangeMode" option the second click doesn't seem to be recognized, UI doesn't get updated and "selectedChange" output isn't triggered.
Is there a workaround? The stackblitz link doesn't seem to include source code.

**Comment by SaturnTeam** [comment]
I don't have any due to official material doesn't support this mode.
You can add this feature and make a pull request for that in this repo

**Comment by beyondsanity** [comment]
https://github.com/SaturnTeam/saturn-datepicker/pull/87

**Comment by SaturnTeam** [comment]
7.4.0
