### ISSUE TITLE
Not working the CSS or SCSS in angular 7 Material 7.0.4

### ISSUE THREAD

**Issue by svonnidmeg** [SaturnTeam/saturn-datepicker#47]
The Saturn component works fine but not looks fine in Angular 7 Material 7.0.4.
The classes:

- mat-calendar-cell-semi-selected
- mat-calendar-body-semi-selected

and all CSS classes of the saturn (see attachements). The td element write the name of the class, but the CSS, SCSS not exists and can't be created by me in a apart CSS, SCSS

![semi-selected-css-not-working](https://user-images.githubusercontent.com/7086944/48828961-60727000-ed71-11e8-9dce-439da846b113.png)
![semi-selected-css-not-working-inspector](https://user-images.githubusercontent.com/7086944/48828963-60727000-ed71-11e8-816c-f68860acbd4e.png)

**Comment by Laurensvdw** [comment]
I am on version 7.0.3 of Angular and Material. For me it works perfectly, did you include the scss for the datepicker (see last 2 lines of the code)?

`@import '~@angular/material/theming';
$custom-typography: mat-typography-config(
  $font-family: 'Roboto, monospace',
  $headline: mat-typography-level(32px, 48px, 700),
  $body-1: mat-typography-level(16px, 24px, 500)
);
@include mat-core($custom-typography);
$lcdc-primary: mat-palette($mat-blue-gray);
$lcdc-accent:  mat-palette($mat-teal);
$lcdc-warn:  mat-palette($mat-red);
// Create the theme object (a Sass map containing all of the palettes).
$lcdc-theme: mat-light-theme($lcdc-primary, $lcdc-accent, $lcdc-warn);
@include angular-material-theme($lcdc-theme);

@import '~saturn-datepicker/theming';
@include sat-datepicker-theme($lcdc-theme);
`

**Comment by svonnidmeg** [comment]
These 2 lines was 1st I tried, but nothing happens. Added into app.scss, into app.component.scss,... nothing

When I see inspector in Chrome, the classes are added into TD as textt, but nothing appears in CSS.

**Comment by Laurensvdw** [comment]
Have you made sure SCSS is enabled in angular.json?
```
"schematics": {
  "@schematics/angular:component": {
      "styleext": "scss"
  }
},
```
I added everything in styles.scss (also needs to be present in angular.json), as the styles are required in the whole application, not on one component.
```
"styles": [
    "src/styles.scss"
],
```

**Comment by svonnidmeg** [comment]
Sorry... it's working now including these 2 lines in a theme.scss instead into app.component.scss... but now the style can't be modified component by component (if I want semi-selected in red on a specific page and blue in other page of same app)

**Comment by Laurensvdw** [comment]
Normally you can. Take a look at the [Angular Material theming guide](https://material.angular.io/guide/theming#multiple-themes).

I guess providing another theme to the sat-datepicker within a sub class can achieve your goal?
```
.another-theme {
  @include angular-material-theme($another-theme);
  @include sat-datepicker-theme($another-theme);
}
```

**Comment by svonnidmeg** [comment]
Thx!
