### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rebigliazzi** [SaturnTeam/saturn-datepicker#49]
Good night, I've done all the steps and when running the app, the following error occurs to me, can you help me?

Tks

rror: Template parse errors:
Can't bind to 'satDatepicker' since it isn't a known property of 'input'. ("
    <input matInput
        placeholder="Choose a date"
        [ERROR ->][satDatepicker]="picker"
        [value]="date">
    <sat-datepicker #picker [rangeMode]="true"></sat"):

**Comment by SaturnTeam** [comment]
try 7.0.1 and look at example https://stackblitz.com/edit/angular-4cfnyl?file=src%2Fapp%2Fhello.component.ts

**Comment by rebigliazzi** [comment]
Done , but still not work :(

**Comment by SaturnTeam** [comment]
I think you forget import smth

**Comment by rebigliazzi** [comment]
Tks , smth ?

**Comment by SaturnTeam** [comment]
May be you forget to import modules

**Comment by rebigliazzi** [comment]
All modules imported 
https://pastebin.com/ga0pdGuZ

**Comment by SaturnTeam** [comment]
It seems ok. Try to copy paste a code from the demo. I don't know what is wrong
