### ISSUE TITLE
closeAfterSelection false is not working

### ISSUE THREAD

**Issue by naamabara** [SaturnTeam/saturn-datepicker#50]
Hi there! I set closeAfterSelection to be false but still the window close immediately.
here is the code:
<mat-form-field>
  <input matInput
         placeholder="Choose a range"
         [satDatepicker]="picker">
  <sat-datepicker #picker [rangeMode]="true" [closeAfterSelection]="false" [endDate]=""></sat-datepicker>
  <sat-datepicker-toggle matSuffix [for]="picker" ></sat-datepicker-toggle>
</mat-form-field>

**Comment by SaturnTeam** [comment]
7.0.1 version?

**Comment by mieszczans** [comment]
> 7.0.1 version?

Yes

**Comment by naamabara** [comment]
yes.

**Comment by SaturnTeam** [comment]
Fixed in 7.0.2
