### ISSUE TITLE
Error CanColor

### ISSUE THREAD

**Issue by mieszczans** [SaturnTeam/saturn-datepicker#51]
I got an error after install package by npm and copy/paste template from 'It's awesome, but how to use it?'.

> ERROR in node_modules/saturn-datepicker/datepicker/datepicker.d.ts(12,20): error TS2305: Module ${path_here} has no exported member 'CanColorCtor'. 
node_modules/saturn-datepicker/datepicker/datepicker.d.ts(42,22): error TS2420: Class 'SatDatepickerContent<D>' incorrectly implements interface 'CanColor'.
  Property 'color' is missing in type 'SatDatepickerContent<D>'.

**Comment by SaturnTeam** [comment]
#48

**Comment by SenAlexandru** [comment]
I've just got this error while upgrading from Angular 9 to 10
```
ERROR in node_modules/saturn-datepicker/datepicker/datepicker.d.ts:57:22 - error TS2420: Class 'SatDatepicker<D>' incorrectly implements interface 'CanColor'.
  Property 'defaultColor' is missing in type 'SatDatepicker<D>' but required in type 'CanColor'.

57 export declare class SatDatepicker<D> implements OnDestroy, CanColor {
                        ~~~~~~~~~~~~~

  node_modules/@angular/material/core/common-behaviors/color.d.ts:15:5
    15     defaultColor: ThemePalette | undefined;
           ~~~~~~~~~~~~
    'defaultColor' is declared here.
```

**Comment by mageshwaran-p** [comment]
> from Angular 9 to 10

did you find a fix?

**Comment by gauriz** [comment]
Guys, I don't think it is fixed. Is it ?

**Comment by kshetline** [comment]
I'm getting the same error too, and the older bug that's already closed two years ago doesn't fix this new problem.
