### ISSUE TITLE
Problem with building by Gulp

### ISSUE THREAD

**Issue by mieszczans** [SaturnTeam/saturn-datepicker#52]
I have bought theme so if I need to use variables from theme (in this case I need to add:
`@import '~saturn-datepicker/theming';
@include sat-datepicker-theme($theme);` to my main style.scss) and when I hit:
gulp --prod --angular

I get an error:
Message:
    ..\src\sass\framework\vendors\material-angular\_custom.scss
Error: File to import not found or unreadable: ~saturn-datepicker/theming.
        on line 32 of ../src/sass/framework/vendors/material-angular/_custom.scss
        from line 9 of ../src/sass/framework/vendors/material-angular/mat.scss
        from line 21 of ../src/sass/demo/default/style.bundle.css
>> @import '~saturn-datepicker/theming';
   ^

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ..\src\sass\framework\vendors\material-angular\_custom.scss
Error: File to import not found or unreadable: ~saturn-datepicker/theming.
        on line 32 of ../src/sass/framework/vendors/material-angular/_custom.scss
        from line 9 of ../src/sass/framework/vendors/material-angular/mat.scss
        from line 21 of ../src/sass/demo/default/style.bundle.css
>> @import '~saturn-datepicker/theming';
   ^

Saturn-datepicker version: 6.1.1
Angular 6

![screen](https://user-images.githubusercontent.com/20318051/49740485-9a5dd480-fc94-11e8-8a23-d0a8454f8261.png)

**Comment by SaturnTeam** [comment]
Sorry, I'm not familiar with Gulp. You could try `@import '~saturn-datepicker/_theming';`

**Comment by yandiro** [comment]
For those looking for an answer (like I just was).

You have to import in your styles.scss inside src folder,  not in your component.
This did the trick for me.

`@import '~saturn-datepicker/bundle.css';`
