### ISSUE TITLE
Change class dynamically while picker is open

### ISSUE THREAD

**Issue by sancaruso** [SaturnTeam/saturn-datepicker#54]
Hello,
I would like to use sat-datepicker with option [closeAfterSelection]="false". I also need to add a custom class with [dateClass] but I need this class to dynamically updates while the picker is opened (after a selection is made).
At this time the dateClass is only updated when we open the picker.

Is it possible to add the ability of dynamically refreshing the dateClass while the picker is open?

**Comment by SaturnTeam** [comment]
Yeah, it's possible. You can make a pull request with recalculating cells (`_createWeekCells`, after range selection in file https://github.com/SaturnTeam/saturn-datepicker/blob/master/saturn-datepicker/src/datepicker/month-view.ts .
Let's try. If you failed, may be I'll do this feature later

**Comment by sancaruso** [comment]
How do you run the demo in the repository to test the changing? When I run `ng serve` at the root of the repository I have this error:
`Could not determine a single project for the 'serve' target.`
And when running `ng serve dev` it compiles but then the application don't run and I have this error in the console:
`Uncaught Error: Can't resolve all parameters for ApplicationModule: (?).`

**Comment by sancaruso** [comment]
Sorry, it's ok. The line `import 'core-js/es7/reflect';` was removed from `package.json`, I don't know why. I put it again.

**Comment by SaturnTeam** [comment]
I think it's resolved
