### ISSUE TITLE
Calendar popup alignment issue

### ISSUE THREAD

**Issue by Indrani-Kilaru** [SaturnTeam/saturn-datepicker#6]
Calendar popup is always opening in top left corner of the window. It should be relative to the input field. could you please make it relative to input field.

**Comment by SaturnTeam** [comment]
I know why this happen and how to fix it. But I can't compile library for npm.  Package tool isn't adapted to angular 6 yet.

**Comment by SaturnTeam** [comment]
Try 1.0.7

**Comment by Indrani-Kilaru** [comment]
Thanks.. working with 1.0,7..
