### ISSUE TITLE
In rangeMode, select a single date if only selecting the first and then closing the picker

### ISSUE THREAD

**Issue by sancaruso** [SaturnTeam/saturn-datepicker#64]
On my application I would like that, in range mode, if a user select a date and then closes the date-picker, the range with this single date is selected. I need to modify this package to achieve that. I can do it several ways:
- I can implement this behavior by default
- I can implement this behavior but with an option to give the possibility of use this behavior, or keep the current behavior
- I can just trigger an event when the first date is selected, then I manage with this event in my application.

Please @SaturnTeam tell me what way you prefer I implement.

**Comment by sancaruso** [comment]
https://github.com/SaturnTeam/saturn-datepicker/pull/68

**Comment by SrinivasaKK** [comment]
is there any way I can detect a first selected date?
My range is dynamic and it depends on the first selected date. So I need to detect the first selected date event and limit the range for end date.
