### ISSUE TITLE
Regression : range selection with keyboard don't work anymore

### ISSUE THREAD

**Issue by sancaruso** [SaturnTeam/saturn-datepicker#66]
There is a regression since my commit https://github.com/SaturnTeam/saturn-datepicker/commit/9d54ff1cc276d1effdb17f35a810aeb75d0380d8
With options `closeAfterSelection` and `rangeMode`, the picker closes when we select the first date with keyboard.

**Comment by sancaruso** [comment]
@SaturnTeam this has to do with this commit:
https://github.com/SaturnTeam/saturn-datepicker/commit/eb439c4d13d23463ad8d16da7d8d67aeb6b2b025
I am not sure how to fix it.

**Comment by sancaruso** [comment]
Indeed, wrapping the
```
            if (!this.beginDateSelected) {
              this._userSelection.emit();
            }
            if (this.beginDateSelected || !this.closeAfterSelection) {
              this._focusActiveCell();
            }
```
in a setTimeout solves the problem, but that isn't satisfying. I look for a better way. If any idea please tell me.

**Comment by SaturnTeam** [comment]
May be it's requires more check in 
            if (!this.beginDateSelected) {
              this._userSelection.emit();
            }

**Comment by sancaruso** [comment]
Actually this.beginDateSelected should be true but is false (because it is not set anymore in this component, but in the parent component, and so I guess it is set later).

A solution would be to double the property (have an `@Input() beginDateSelected` and a `private _beginDateSelected`) and changing `_beginDateSelected` in the function `_dateSelected` while emiting the event that will change `beginDateSelected` in the parent component.

That is not very nice but I don't know if there is a better way.

**Comment by SaturnTeam** [comment]
Well, I don't have a better idea too

**Comment by sancaruso** [comment]
Ok, so that's it:
https://github.com/SaturnTeam/saturn-datepicker/pull/67

**Comment by SaturnTeam** [comment]
7.1.2
