### ISSUE TITLE
Angular 8 Ivy compiler error

### ISSUE THREAD

**Issue by akolybelnikov** [SaturnTeam/saturn-datepicker#71]
#### Install the latest Angular CLI release with
`npm i -g @angular/cli@8.0.0-beta.2`

#### Enable the opt-in Ivy compiler in a new project with
`ng new my-project --experimentalIvy=true`

#### Run `npm install saturn-datepicker --save` in the project root.

`Compiling saturn-datepicker - fesm2015
Error: Errors parsing template: Unexpected closing tag "sat-month-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (""\n      (selectedChange)=\"_dateSelected($event)\"\n      (_userSelection)=\"_userSelected()\">\n  [ERROR ->]</sat-month-view>\n\n  <sat-year-view\n      *ngSwitchCase=\"'year'\"\n      [(activeDate)]=\"activeD"): fesm2015/saturn-datepicker.js@2463:748, Unexpected closing tag "sat-year-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("_monthSelectedInYearView($event)\"\n      (selectedChange)=\"_goToDateInView($event, 'month')\">\n  [ERROR ->]</sat-year-view>\n\n  <sat-multi-year-view\n      *ngSwitchCase=\"'multi-year'\"\n      [(activeDate)"): fesm2015/saturn-datepicker.js@2463:1104, Unexpected closing tag "sat-multi-year-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("arSelectedInMultiYearView($event)\"\n      (selectedChange)=\"_goToDateInView($event, 'year')\">\n  [ERROR ->]</sat-multi-year-view>\n</div>\n",
                host: {
                    'class': 'mat-calendar"): fesm2015/saturn-datepicker.js@2463:1473, Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("w($event)\"\n      (selectedChange)=\"_goToDateInView($event, 'year')\">\n  </sat-multi-year-view>\n[ERROR ->]</div>\n",
                host: {
                    'class': 'mat-calendar',
"): fesm2015/saturn-datepicker.js@2463:1497`

**Comment by SaturnTeam** [comment]
Interesting. I think I fix it by the end of week.

**Comment by akolybelnikov** [comment]
It could be a bug with `ivy`: https://github.com/angular/angular/issues/28843

**Comment by SaturnTeam** [comment]
I think we need to wait while 8.0 will be released
