### ISSUE TITLE
Change the date format of Saturn date picker

### ISSUE THREAD

**Issue by vinutawadi** [SaturnTeam/saturn-datepicker#73]
I am trying to change the format of a date to "medium" -> "06 Oct 2018" to this format. How to change the format in reactive forms

`  <input matInput placeholder="Choose range" [satDatepicker]="rangePicker" [max]="today" formControlName="defaultRange">
          <sat-datepicker #rangePicker [rangeMode]="true" [closeAfterSelection]="true" orderPeriodLabel="date" [opened]="true"></sat-datepicker>
          <sat-datepicker-toggle matSuffix [for]="rangePicker"></sat-datepicker-toggle>`

**Comment by SaturnTeam** [comment]
See changing date format from material datepicker

**Comment by vinutawadi** [comment]
I tried implementing the material date picker date format, it didn't work

**Comment by RajuIO** [comment]
there is no such type of format for material date picker,
please use this as reference : 

**1) https://codinglatte.com/posts/angular/custom-date-formats-angular-material-date-picker/**

**2) https://angular-material-date-picker.s3-us-west-2.amazonaws.com/index.html**
