### ISSUE TITLE
<mat-form-field appearance="standard">

### ISSUE THREAD

**Issue by Moomoobooboo** [SaturnTeam/saturn-datepicker#75]
No worries... was actually angular issue -> appearance="standard" -> label animation is gone

**Comment by SaturnTeam** [comment]
What?

**Comment by Moomoobooboo** [comment]
This is not working label animation in angular:

<mat-form-field appearance="standard">
  <input matInput [matDatepicker]="picker" placeholder="Choose a date">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>

This is working label animation:

<mat-form-field>
  <input matInput [matDatepicker]="picker" placeholder="Choose a date">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
