### ISSUE TITLE
Print the selected range of dates

### ISSUE THREAD

**Issue by JayashreeKrishanveni** [SaturnTeam/saturn-datepicker#76]
How do display /print the selected range of dates using this date range picker ? Say if I select 8/5/2018 - 8/10/2018 ; how do I display the all the dates selected range  below like 8/5 8/6 8/7 8/9 8/10 apart from 8/5/2018 - 8/10/2018 that appears in the input box ?

**Comment by SaturnTeam** [comment]
datepicker returns a value. use it. if you don't know how - ask stackoverflow

**Comment by JayashreeKrishanveni** [comment]
I tried implementing using .value it didn't return the values. Please give more insights.

**Comment by SaturnTeam** [comment]
> I tried implementing ; it returned the
> first and last date along with time , how to return only the date value ?

Just use formatting. Angular Date pipe for example
