### ISSUE TITLE
Date range selection doesn't highlight initially after change

### ISSUE THREAD

**Issue by Cacanny** [SaturnTeam/saturn-datepicker#77]
This looks similar to other issues but what happens is, I have function that changes the 'range' out of the view template. It changes the range selection BUT it doesn't update the view (it doesn't highlight the selection) ONLY if I start hovering over the calendar. 

Is there a way to trigger this events immediately? 

 ```
onDateRangesChange(calendar: SatCalendar<Date>, range: SatDatepickerRangeValue<Date>): void {
    calendar.beginDate = range.begin;
    calendar.endDate = range.end;
    this.range = range;
    this.updateDateRange.emit(this.range);
  }

  selectCurrentMonth(): void {
    const newDate = new Date();
    this.range = {
      begin: new Date(newDate.getFullYear(), newDate.getMonth(), 1),
      end: new Date(newDate.getFullYear(), newDate.getMonth() + 1, 0),
    };

    this.onDateRangesChange(this.calendar, this.range);
  }
```

```
 <sat-calendar
    #calendar
    [dateFilter]="filterdate"
    [rangeMode]="true"
    [minDate]="minDate"
    [maxDate]="maxDate"
    orderPeriodLabel="month"
    (dateRangesChange)="onDateRangesChange(calendar, $event)"
  ></sat-calendar>
```

![20190320_114205](https://user-images.githubusercontent.com/8970283/54678384-55540480-4b05-11e9-9ceb-ac7f19efc20c.gif)

**Comment by SaturnTeam** [comment]
How do you pass the value into datepicker? Do you create a new object?
And could you provide an online example?

**Comment by Cacanny** [comment]
By providing the begin and end date on the calendar, at the Viewchild.

`  @ViewChild('calendar') calendar: SatCalendar<Date>;`

**Comment by SaturnTeam** [comment]
Do you change date instances?On Mar 20, 2019 12:39 PM, Cacanny <notifications@github.com> wrote:By providing the begin and end date on the calendar, at the Viewchild.
  @ViewChild('calendar') calendar: SatCalendar<Date>;

**Comment by Cacanny** [comment]
Not sure what you mean, I mean, I change the calendar.beginDate and calendar.endDate, so yes?

**Comment by SaturnTeam** [comment]
No. You should pass them as variables in template. In angular wayOn Mar 20, 2019 4:24 PM, Cacanny <notifications@github.com> wrote:Not sure what you mean, I mean, I change the calendar.beginDate and calendar.endDate, so yes?

**Comment by Cacanny** [comment]
I bind it with #calandar, why would it be different with variables in the template?

**Comment by SaturnTeam** [comment]
because lifecycle event may not be triggered.

**Comment by Cacanny** [comment]
This makes sense, so I should bind the begin and endDate to the inputters of the calendar? like so:

 ```
<sat-calendar
    #calendar
    [dateFilter]="filterdate"
    [rangeMode]="true"
    [beginDate] = "beginDate" <-
    [endDate]="endDate" <-
    [minDate]="minDate"
    [maxDate]="maxDate"
    orderPeriodLabel="month"
    (dateRangesChange)="onDateRangesChange(calendar, $event)"
  ></sat-calendar>
```

**Comment by SaturnTeam** [comment]
yes

**Comment by Cacanny** [comment]
That did the trick, sorry for the inconvenience and thanks for your help! Great library btw, hopefully the Angular team picks it up soon and make it native.
