### ISSUE TITLE
Change format guide can be simplified

### ISSUE THREAD

**Issue by fetis** [SaturnTeam/saturn-datepicker#78]
Currently, the readme says that you have to use moment adapter if you want to get a different date format. That is not the only option. Since the `SaturnDatepicker` uses native date adapter, you can just provide your own implementation of this adapter with small customization of `format` function and get new format both in `MaterialDatepicker` and `SaturnDatepicker`.

I did this in my project and it work like a charm.

here's the sample code

```typescript
export class MyDateAdapter extends NativeDateAdapter {
  private datePipe = new DatePipe(this.locale);

  format(date: Date, displayFormat: any): string {
    if (typeof displayFormat === 'string') {
      const result = this.datePipe.transform(date, displayFormat);
      return result ? result : '';
    } else {
      return super.format(date, displayFormat);
    }
  }
}
```

**Comment by SaturnTeam** [comment]
Added to readme

**Comment by VukMNE** [comment]
@fetis Could you please show an example of how to use your code? Where should I use this MyDateAdapter class? I want to display the date in format: 'DD.MM.YYYY', but I am having trouble to find a helpful guide for changing the date format of a saturn-datepicker.

**Comment by fetis** [comment]
@VukMNE we have a module that registers this provider
```
import { DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE } from '@angular/material/core';
...
@NgModule({
  exports: [
    MatDatepickerModule,
  ],
  providers: [
    { provide: DateAdapter, useClass: MyDateAdapter, deps: [ MAT_DATE_LOCALE, Platform ] },
  ]
})
export class XXXDatepickerModule { }
```

and you import this module like any other modules and you datepicker now support custom date format
