### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by oscarpedrero** [SaturnTeam/saturn-datepicker#8]
Hi,

I tried to change locale format for the display date in Spanish format, but datepicker range don't get locale with 

`this.adapter.setLocale('es');`

Normal datepicker give locale but datepicker range doesn't in same html.

Can you help me? Thanks

<img width="821" alt="captura de pantalla 2018-04-14 a las 12 33 42" src="https://user-images.githubusercontent.com/6031863/38767371-292b888c-3fe0-11e8-860a-b444f63837a1.png">

**Comment by SaturnTeam** [comment]
`adapter` is instance of `SatNativeDateAdapter`?

**Comment by oscarpedrero** [comment]
How can import `SatNativeDateAdapter` ?

`import {SatNativeDateAdapter} from 'saturn-datepicker'; `

`[Error] has no export member SatNativeDateAdapter`

**Comment by oscarpedrero** [comment]
With this 

import {DateAdapter} from 'saturn-datepicker';

Work like a charm!

Thks @SaturnTeam
