### ISSUE TITLE
The dateClass function is not invoked if month next/ month prev arrows clicked.

### ISSUE THREAD

**Issue by cbejenaru** [SaturnTeam/saturn-datepicker#80]
The dateClass function is not invoked when changing the month using arrows. The styles are applied only after clicking on a calendar cell.

Have to remark that I use sat-calendar apart from date piker.

`     <sat-calendar *ngIf="availability" 
[selected]="selectedDate"
          (selectedChange)="onDateSelect($event)" [dateClass]="isAvailable" (click)="onMonthChange($event)" #calendar>
        </sat-calendar>`

![ezgif-2-aa6bc2bcc447](https://user-images.githubusercontent.com/40862172/55167122-106d4500-5179-11e9-9ca7-eb37c9a3e109.gif)

**Comment by SaturnTeam** [comment]
@cbejenaru  Try 7.2.1 version
