### ISSUE TITLE
Passing date to Input with Locale - bug

### ISSUE THREAD

**Issue by tomasznastaly** [SaturnTeam/saturn-datepicker#81]
I found a bug - for e.g if you set locale to DE, and type in date input a date range. e.g 20/10/2017 - 22/10/2017, then date is treated always as US format - 10/20/2017 - 10/22/2017 and we get the error because such date doesn't exist, of course. 

Any way to fix it?

**Comment by SaturnTeam** [comment]
Yes. Use material moment.js dateadapter for example. See material documentaion and readme of this repo
