### ISSUE TITLE
How to set range value dynamically

### ISSUE THREAD

**Issue by tcuje** [SaturnTeam/saturn-datepicker#84]
My datepicker in the template is defined as follows:
```
<input matInput [placeholder]="'select date here"
                           [satDatepicker]="picker" readonly
                           [ngModel]="myParams.dateRange" #dateRange="ngModel" autocomplete="off"
                           (dateInput)="onDateFilterChange(dateRange.value)" (click)="picker.open()">
```

In the code I try to update the datepicker dynamically with:
```
            this.myParams.dateRange.begin = new Date(2018, 7, 5);
            this.myParams.dateRange.end = new Date(2018, 7, 25);
```

The datepicker only shows the dates, when clicked for the first time.

How can I debug this? Whats the problem here? Why is the range not shown?

**Comment by SaturnTeam** [comment]
See examples of angular material datepicker. ` this.myParams.dateRange = {begin: date, end: date}`

**Comment by tcuje** [comment]
You mean this? https://stackblitz.com/edit/angular-4cfnyl

I did, but still no clue and isn't this: `this.myParams.dateRange = {begin: date, end: date}` just the same like 
```
this.myParams.dateRange.begin = new Date(2018, 7, 5);
this.myParams.dateRange.end = new Date(2018, 7, 25);
```

**Comment by SaturnTeam** [comment]
Because you are editing the same object and angular thinks that value has not changed.

**Comment by tcuje** [comment]
YES! Thats the issue! Thank you very much! Spend hours on that one...

Using:

`this.myParams.dateRange = {begin: new Date(startMilliseconds), end: new Date(endMilliseconds)}`

instead of:

```
this.myParams.dateRange.begin = new Date(startMilliseconds);
this.myParams.dateRange.end = new Date(endMilliseconds);
```

fixed it.
