### ISSUE TITLE
Error when build prod

### ISSUE THREAD

**Issue by oscarpedrero** [SaturnTeam/saturn-datepicker#9]
When run `npm run build --prod --environment prod` i have this error:

`[ERROR in : Unexpected value 'SatNativeDateModule in /xxx/xxx/xxx/xxxx/node_modules/saturn-datepicker/datetime/index.d.ts' imported by the module 'AppModule in /xxx/xxx/xxx/xxxx/src/app/app.module.ts'. Please add a @NgModule annotation.](url)`

Can you help me?

**Comment by SaturnTeam** [comment]
Yeah. Use source code instead (two folders from `/src`). I know about this problem. I'm waiting for angular 6 and while `ng-packagr` will work with it.

**Comment by oscarpedrero** [comment]
Ok, copy datetime y datepicker folder to src, right?

Import SatNativeDateModule from this directory?

Thks for your support!

**Comment by SaturnTeam** [comment]
Yep
