### ISSUE TITLE
How can i set the min and max value in the inline datepicker?

### ISSUE THREAD

**Issue by ils-nikhilp** [SaturnTeam/saturn-datepicker#93]
I have gone through the basic documentation, but didn't find the way or syntax to set the min and max value in the inline datepicker (in sat-calender). So, can you please help me out in it.

**Comment by SaturnTeam** [comment]
There is no way;(On Jun 25, 2019 10:33 PM, Nikhil Paliwal <notifications@github.com> wrote:I have gone through the basic documentation, but didn't find the way or syntax to set the min and max value in the inline datepicker (in sat-calender). So, can you please help me out in it.

**Comment by ils-nikhilp** [comment]
Can you provide any way to implement this? or can you add this feature in it. As, in most of the cases it required to disable the date as per the min and max value.

**Comment by ils-nikhilp** [comment]
Got the solution by doing some R&D by own. Now it is resolved.

**Comment by MKRNaqeebi** [comment]
@ils-nikhilp How you solved it I am facing same issue

**Comment by ils-nikhilp** [comment]
For min and max value it has the same option as mat-calendar.

**Comment by MKRNaqeebi** [comment]
Got it thanks
@SaturnTeam please improve documentation add use method in sample code
