### ISSUE TITLE
how add language change

### ISSUE THREAD

**Issue by shahbaazchaviwale** [SaturnTeam/saturn-datepicker#94]
based on local storage how to setup language change in calendar. I have 2 language "de-DE", "en-US"

**Comment by niazlake** [comment]
Also, I can't change the local language.

**Comment by SaturnTeam** [comment]
see original material and angular datepicker documentation for using other languages.  Saturn datepicker have pretty the same API

**Comment by niazlake** [comment]
But this didn't work

![image](https://user-images.githubusercontent.com/10130630/60497552-bae78d80-9cbd-11e9-9766-861afd3f5683.png)


![image](https://user-images.githubusercontent.com/10130630/60497575-c9ce4000-9cbd-11e9-8a63-a8ffdb2d4750.png)

As you see local language didn't change.
