### ISSUE TITLE
Localization didn't work

### ISSUE THREAD

**Issue by niazlake** [SaturnTeam/saturn-datepicker#95]
![60497552-bae78d80-9cbd-11e9-9766-861afd3f5683](https://user-images.githubusercontent.com/10130630/60498958-3a765c00-9cc0-11e9-90d2-95919a3e109a.png)
![60497575-c9ce4000-9cbd-11e9-8a63-a8ffdb2d4750](https://user-images.githubusercontent.com/10130630/60498960-3ba78900-9cc0-11e9-8aa5-1e5df4e12877.png)

As you see the local language didn't change. I think the API route didn't work correctly.

**Comment by SteffenSchwaiger** [comment]
Well I think the problem is that there is no "ru-RU" locale id to begin with. Just try _ru_ only.

```
{provide: MAT_DATE_LOCALE, useValue: 'ru'},
{provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]}
```

![image](https://user-images.githubusercontent.com/5320760/64202269-04f11900-ce91-11e9-886d-0f3a85fa345e.png)
