### ISSUE TITLE
Change value to UTC

### ISSUE THREAD

**Issue by devitlie** [SaturnTeam/saturn-datepicker#97]
Hi, I am trying to change the date value to UTC, but somehow there is an error when I am using DateAdapter from saturn-datepicker. Is it possible to do this in saturn-datepicker? if so, could you tell me how to do it? Thank you.

Here are my codes:
```
import { SatDatepickerModule, SatNativeDateModule, MAT_DATE_LOCALE, DateAdapter } from 'saturn-datepicker'
import { MAT_MOMENT_DATE_ADAPTER_OPTIONS, MomentDateAdapter } from '@angular/material-moment-adapter';

@NgModule({
    imports: [
        SatDatepickerModule
    ],
    providers: [
        { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE] },
        { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } }
    ],
})
```
and here is the error message:
```
ERROR TypeError: format.replace is not a function
    at expandFormat (moment.js:628)
    at formatMoment (moment.js:613)
    at Moment.format (moment.js:3375)
    at MomentDateAdapter.format (material-moment-adapter.js:218)
    at SatCalendarHeader.get periodButtonText [as periodButtonText] (saturn-datepicker.js:2012)
    at Object.eval [as updateRenderer] (SatCalendarHeader.html:5)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:36078)
    at checkAndUpdateView (core.js:35061)
    at callViewAction (core.js:35421)
    at execComponentViewsAction (core.js:35349)
```

**Comment by SteffenSchwaiger** [comment]
Try the following:
```
{provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: {useUtc: true}},
{provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE, MAT_MOMENT_DATE_ADAPTER_OPTIONS]}
```

You have to provide the _MAT_MOMENT_DATE_ADAPTER_OPTIONS_ provider token to the _MomentDateAdapter_ class

**Comment by Stehos** [comment]
@SteffenSchwaiger  Hi Steffen, I have the same issue, please could you help us? Thanks.

**Comment by pugachovY** [comment]
@Stehos 
Hi, today a have the same problem.
Don`t forget provide MAT_DATE_FORMATS, it help for me [FAQ] (https://github.com/SaturnTeam/saturn-datepicker) helps you

In the end I have this code
`
import { SatDatepickerModule, SatNativeDateModule, MAT_DATE_LOCALE, MAT_DATE_FORMATS, DateAdapter } from 'saturn-datepicker';
import { MAT_MOMENT_DATE_FORMATS, MomentDateAdapter, 
    MatMomentDateModule, MAT_MOMENT_DATE_ADAPTER_OPTIONS } from '@angular/material-moment-adapter';

...

{   provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
{   provide: MAT_DATE_LOCALE, useValue: 'en-gb' },
{   provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE, MAT_MOMENT_DATE_ADAPTER_OPTIONS]},
        {provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS}`

**Comment by Stehos** [comment]
Hi @pugachovY  thank you for your comment. 
I solved my issues and I moved on with the following config:

Imports:
`import { MatDatepickerModule } from '@angular/material/datepicker'; 
import { DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE, SatDatepickerModule, SatNativeDateModule  } from 'saturn-datepicker'
import { MAT_MOMENT_DATE_ADAPTER_OPTIONS, MomentDateAdapter, MatMomentDateModule } from '@angular/material-moment-adapter';`

And in the Providers array I have this:
`              {provide: MAT_DATE_LOCALE, useValue: 'en-GB'},
              {provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: {useUtc: true}}`
